SDP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from SDP import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("markets/", include("markets.urls")),
    path("", views.index),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

markets/urls.py
from django.urls import path
from markets import views

app_name = "markets"
urlpatterns = [
    path("", views.market_list, name = "market_list"),
    path("add/", views.market_add, name = "market_add"),
    path("<int:market_id>/", views.market_detail, name = "market_detail"),
    # path("tags/<str: tag_name>/", views.nearby_tag_markets, name = "tag_search_list"),
    path("tags/<str:tag_name>/", views.nearby_tag_markets, name = "tag_search_list"),
    path("<int:market_id>/like/", views.market_like, name = "market_like"),
    path("<int:market_id>/comment_add/", views.comment_add, name="comment_add"),
    path("<int:market_id>/edit/", views.market_edit, name = "market_edit"),
    path("<int:comment_id>/comment_delete/", views.comment_delete, name = "comment_delete"),
    path("<int:market_id>/delete/", views.market_delete, name = "market_delete"),
]

markets/models.py
from django.db import models

# Create your models here.

class Market(models.Model):
    user = models.ForeignKey("users.User", on_delete = models.CASCADE, related_name = 'markets') # user 모델과 foreign key 연결 
    name = models.CharField(max_length=32, verbose_name= '상호명') 
    address = models.CharField(max_length= 128, verbose_name= '주소') 
    call_number = models.CharField(max_length=15, blank= True, null = True, verbose_name= '전화번호') 
    content = models.TextField(verbose_name= '가게 소개', blank= True, null = True) # 업로드한 사진들(MarketImage)에 대한 소개 
    tags = models.ManyToManyField("markets.HashTag", max_length= 50, blank= True, verbose_name= '해시태그 목록') 
    # festivals = models.ManyToManyField("markets.Festival", on_delete= models.SET_NULL, related_name = 'markets'),
    festivals = models.ManyToManyField("markets.Festival", related_name = 'markets'),

class MarketImage(models.Model):
    post = models.ForeignKey("markets.Market",
                             verbose_name = "이미지",
                             on_delete = models.CASCADE)
    photo = models.ImageField("사진", upload_to = "post")
    

class HashTag(models.Model):
    name = models.CharField(max_length=50, verbose_name="태그명",)

    def __str__(self):
        return self.name
    
class Region(models.Model):
    name = models.CharField(max_length=10, unique=True)

class Festival(models.Model):
    name = models.CharField(max_length= 50, verbose_name = "축제명")
    start_month = models.IntegerField()
    middle_month = models.IntegerField()
    end_month = models.IntegerField()
    address = models.CharField(max_length = 128, verbose_name = '축제주소')
    location = models.CharField(max_length = 5, verbose_name = '축제지역')
    description = models.TextField(verbose_name = '축제소개')
    festival_thumbnail = models.ImageField(verbose_name= '축제 썸네일', upload_to = "festivals/thumbnail", blank = True)
    season = models.IntegerField()
    region = models.ForeignKey("markets.Region", on_delete = models.SET_NULL, null = True )

    def __str__(self):
        return self.name
    
    def region_from_location(self,location):
        if '서울' in location or '인천' in location  or '경기' in location :
            return Region.objects.get(name="수도권")
        
        elif '충청' in location or '대전' in location or '세종' in location:
            return Region.objects.get(name="충청권")
        
        elif '전라' in location or'광주' in location or '전북' in location:
            return Region.objects.get(name="호남권")
        
        elif '강원' in location:
            return Region.objects.get(name="강원권")
        
        elif '경상' in location or '대구' in location or '부산' in location or '울산' in location:
            return Region.objects.get(name="영남권")
        
        elif '제주' in location:
            return Region.objects.get(name="제주권")

class Comment(models.Model):
    user = models.ForeignKey("users.User", verbose_name = "작성자", on_delete = models.CASCADE)
    market =  models.ForeignKey("markets.Market", verbose_name = "가게명", on_delete = models.CASCADE)
    content = models.TextField(verbose_name = "리뷰내용")
    created =  models.DateTimeField(verbose_name="작성일시", auto_now_add = True)

markets/forms.py
from django import forms
from markets.models import Market
from users.models import User
from markets.models import Comment

class MarketForm(forms.ModelForm):
    class Meta:
        model = Market
        fields =  [
            "name",
            "call_number",
            "address",
            "content",
        ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "market",
            "content",
        ]
        widgets = {
            "content" : forms.Textarea(
                attrs = {
                    "placeholder" : "리뷰 작성..."
                }
            )
        }

markets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from markets.models import Market,Comment,HashTag,MarketImage,Festival
from markets.forms import MarketForm, CommentForm
from django.http import HttpResponseForbidden

# Create your views here.
def market_list(request):
    markets = Market.objects.all()

    # 템플릿에 전달할 딕셔너리
    context = {
        "markets" : markets,
    }
    return render(request, "markets/market_list.html", context)

def market_add(request):
    if request.method == "POST":

        form = MarketForm(request.POST)

        if form.is_valid():
            market = form.save(commit = False)
            market.user = request.user
            market.save()
            
            for image_file in request.FILES.getlist("images"):
                MarketImage.objects.create(
                    post = market, 
                    photo = image_file,
                )
            # 'tags'에 전달된 문자열을 분리해 HashTag 생성
            tag_string = request.POST.get("tags")
            if tag_string:
                tag_name_list = [tag_name.strip() for tag_name in tag_string.split(",")]
                for tag_name in tag_name_list:
                    tag, _ = HashTag.objects.get_or_create(
                        name = tag_name,
                    )
                    # get_or_create로 생성하거나 가져온 HashTag 객체를 Post의 tags에 추가
                    market.tags.add(tag)

            return redirect("/markets/")
    else:
        form = MarketForm()

    context = {
            'form' : form
        }
    return render(request, "markets/market_add.html", context)

def nearby_tag_markets(request, tag_id, festival_id): # 해시태그를 통해 축제인근 가게를 검색
    try:
        tag = HashTag.objects.get(id = tag_id)
        festival = Festival.objects.get(id = festival_id)
    except HashTag.DoesNotExist:
        tag_markets = Market.objects.none()

    nearby_markets = festival.markets.all()
    tag_markets = nearby_markets.filter(tags=tag)

    context = { "festival" : festival, "tag" : tag, "tag_markets" : tag_markets}

    return render(request, "tag_search_list.html", context)

def comment_add(request, market_id):
    if request.method == "POST":
        form = CommentForm(data = request.POST)    
        print(request.POST)
        print(form)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.user = request.user
            comment.save()            

            if request.GET.get("next"):
                url_next = request.GET.get("next")
            else:
                url_next = request.GET.get("next") or reverse("markets:market_detail", kwargs={"market_id": market_id})
            return redirect(url_next)

    # return redirect(url)
    return redirect(f"/markets/{market_id}/")
    

def market_detail(request, market_id):
    market = Market.objects.get(id = market_id)
    comment_form = CommentForm()
    context = {
        "market" : market,
        "comment_form" : comment_form,
        "market_id" : market_id,
    }
    return render(request,"markets/market_detail.html", context)

def market_like(request, market_id):
    market = Market.objects.get(id = market_id)
    user = request.user
    
    if user.like_markets.filter(id = market_id).exists():
        user.like_markets.remove(market)
    else:
        user.like_markets.add(market)
        
    url_next = request.GET.get("next") or reverse("markets:market_detail", kwargs={"market_id": market_id})
    
    return redirect(url_next)

def market_edit(request, market_id):
    market = get_object_or_404(Market, id=market_id)

    if request.method =="POST":
        form = MarketForm(request.POST, instance = market)
        if form.is_valid():
            market.user = request.user
            market.save()
            return redirect(f"/markets/#market-{market.market_id}")
    else:
        form = MarketForm(instance = market)
            
        context = {
            "form" : form
        }
    
    return render(request, "markets/market_edit.html", context)
    

def comment_delete(request, comment_id):
    comment = Comment.objects.get(id = comment_id)
    if comment.user == request.user:
        comment.delete()

        if request.GET.get("next"):
                url_next = request.GET.get("next")
        else:
                url_next = request.GET.get("next") or reverse("markets:market_detail", kwargs={"market_id": comment.market.id})
        return redirect(url_next)

    
    else:
        return HttpResponseForbidden("이 댓글을 삭제할 권한이 없습니다")
  
def market_delete(request, market_id):
    market = Market.objects.get(id=market_id)
    if market.user == request.user:
        market.delete()
        return redirect("/")
    else:
        return HttpResponseForbidden("이 마켓을 삭제할 권한이 없습니다")

    

templates/markets/market_add.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>Season Dining</title>
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://kit.fontawesome.com/46c538ba64.js" crossorigin="anonymous"></script>
        <link rel= "stylesheet" href="{% static 'css/sdp_style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <!-- <a class="navbar-brand" href="">Start Bootstrap</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li> -->
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/logout/">logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <section class="pt-5">
            <div class="container">
                <div class="p-4 p-lg-5 bg-light rounded-3">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-5 fw-bold m-4">Market add</h1>
                        <div class="m-2 m-lg-4">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div>
                                    <label>사진</label>
                                    <input id="id_images" name="images" type="file" multiple>
                                </div>
                                {{ form.as_p }}
                                <div>
                                    <label for="id_tags">해시태그</label>
                                    <input id="id_tags" name="tags" type="text" 
                                        placeholder="쉼표(,)로 구분하여 여러 태그 입력">
                                   
                                </div>
                                <button type="submit" class="btn btn-primary"> 추가하기 </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

templates/markets/market_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>{{ market.name }} - Season Dining</title>
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://kit.fontawesome.com/46c538ba64.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="{% static 'css/styles_detail.css' %}">
        <link rel="stylesheet" href="{% static 'css/styles_comment.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <!-- <a class="navbar-brand" href="">Start Bootstrap</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#!"></a></li> -->
                        {% if user.business_number %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'markets:market_edit' market_id=market.id %}">market edit</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'markets:market_delete' market_id=market.id%}">market delete</a></li>
                        {% endif %}
                        {% if user.username %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/logout/">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/login/">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <section class="py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="row gx-4 gx-lg-5 align-items-center">
                    {% if image.photo.url %}
                    <div class="post-images splide">
                        <div class="splide__track">
                            <ul class="splide__list">
                                {% for image in market.marketimage_set.all %}
                                    {% if image.photo %}
                                        <li class="splide__slide">
                                            <img src="{{ image.photo.url }}">
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." /></div>
                    {% endif %}
                    <div class="col-md-6">
                        {% for tag in market.tags.all %}
                        <span>#{{ tag.name }}</span>
                        {% endfor %}
                    <h1 class="display-5 fw-bolder">{{ market.name }}</h1>
                    <p class="lead">{{ market.content|linebreaksbr }}</p>
                    <form action="{% url 'markets:market_like' market_id=market.id %}?next={{ action_redirect_url }}"
                    method = "POST">
                    {% csrf_token %}
                        <button type="submit" class="btn btn-outline-dark flex-shrink-0" 
                        {% if user in market.like_users.all %}
                            style="color: red;"
                        {% endif %}>
                        <i class="fa-solid fa-heart"></i>
                        Likes({{ market.like_users.count }})
                        </button>
                    </form>
                    </div>
                </div>
            </div>
        </section>
        <section class="mb-4">
            <div class = "container">
                <span>Comments({{ market.comment_set.count }})</span>
                <div class="card bg-light">

                <ul class="comments">

                    {% for comment in market.comment_set.all %}
                        <li>
                            <span>{{ comment.user.username }}</span>
                            <span>{{ comment.content }}</span>
                        
                    <!-- 댓글 삭제 Form 추가 -->
                        {% if user == comment.user %}
                            <form method="POST" action="/markets/{{ comment.id }}/comment_delete/">                                        
                            {% csrf_token %}
                            <button type="submit">삭제</button>
                            </form>
                        {% endif %}
                        </li>   
                    {% endfor %}
                </ul>
                <div class = "post-comment-create">
                    <form method="POST" action="{% url 'markets:comment_add' market_id=market.id %}?next={{ action_redirect_url }}" >                
                        {% csrf_token %}
                        <input type = "hidden" name = "market" value = "{{ market_id }}">
                        {{ comment_form.content }}
                        <button type="submit" class="btn btn-primary">리뷰 작성</button>
                    </form>
                </div>
                </div>
            </div>
        </section>        
    </body>
</html>

templates/markets/market_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>Season Dining</title>
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://kit.fontawesome.com/46c538ba64.js" crossorigin="anonymous"></script>
        <link rel= "stylesheet" href="{% static 'css/sdp_style.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <!-- <a class="navbar-brand" href="">Start Bootstrap</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li> -->
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/logout/">logout</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <section class="pt-5">
            <div class="container">
                <div class="p-4 p-lg-5 bg-light rounded-3">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-5 fw-bold m-4">Market edit</h1>
                        <div class="m-2 m-lg-4">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-primary"> 수정하기 </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </body>
</html>

templates/markets/market_list.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>Season Dining</title>
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://kit.fontawesome.com/46c538ba64.js" crossorigin="anonymous"></script>
        <link rel= "stylesheet" href="{% static 'css/styles_list.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <!-- <a class="navbar-brand" href="">Start Bootstrap</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#!"></a></li> -->
                        {% if user.business_number %}
                        <li class="nav-item"><a class="nav-link" href="/markets/add/">market add</a></li>
                        {% endif %}
                        {% if user.username %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/logout">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/login/">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">~~~~축제</h1>
                    <p class="lead fw-normal text-white-50 mb-0">미완</p>
                </div>
            </div>
        </header>
        <section class="py-5">
            <div class = "container">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    <!-- for문으로 순회-->
                    {% for market in markets %}
                    {% if market.name != "null" %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            {% if images.photo.url %}
                            <img class="card-img-top" src="{{images.photo.url}}" alt="">
                            {% else %}
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="">
                            {% endif %}
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <h5 class="fw-bolder">{{market.name}}</h5>
                                    <p>{{market.call_number}}</p>
                                    <p>{{market.address}}</p>
                                    <p>{{market.content}}</p>
                                </div>
                            </div>
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'markets:market_detail' market_id=market.id %}">Detail</a></div>
                            </div>
                        </div>
                    </div>
                    <!-- Product actions-->
              
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
        </section>
                    
            

        </section>
    </body>    
</html>

templates/markets/tag_search_list.html
<!DOCTYPE html>
<html lang="ko">
    <body>
    <header>
        <h2>#{{ tag_name }}</h2>
        <div>Market {{ tag_markets.count }} </div> # 해당 해시태그를 가진 가게수 
    </header>
    <div>
        {% for tag_market in tag_markets %}
            {% if tag_market.marketimage_set.first and tag_market.marketimage_set.first.photo %}
                <a href = "{% url 'market_detail' tag_market_id=tag_market.id %}">
                    <img src="{{ tag_market.marketimage_set.first.photo.url }}" alt ="">
                </a>
    </div>
            {% endif %}
            {% empty %}
    </body>
        {% endfor %}
</html>