SDP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from SDP import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("markets/", include("markets.urls")),
    path("", views.index),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

markets/urls.py
from django.urls import path
from markets import views

app_name = "markets"
urlpatterns = [
    path("", views.market_list, name = "market_list"),
    path("add/", views.market_add, name = "market_add"),
    path("<int:market_id>/", views.market_detail, name = "market_detail"),
    # path("tags/<str: tag_name>/", views.nearby_tag_markets, name = "tag_search_list"),
    path("tags/<str:tag_name>/", views.nearby_tag_markets, name = "tag_search_list"),
    path("<int:market_id>/like/", views.market_like, name = "market_like"),
    path("<int:market_id>/comment_add/", views.comment_add, name="comment_add"),
    path("<int:market_id>/edit/", views.market_edit, name = "market_edit"),
    path("<int:comment_id>/comment_delete/", views.comment_delete, name = "comment_delete"),
    path("<int:market_id>/delete/", views.market_delete, name = "market_delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
    </head>
    <body>    
        <h1>test</h1>
    </body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title>Season Dining</title>
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="icon" href="{% static 'assets.favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
        <link rel= "stylesheet" href="{% static 'css/styles.css' %}">
        <script src="https://kit.fontawesome.com/46c538ba64.js" crossorigin="anonymous"></script>
        <link rel= "stylesheet" href="{% static 'css/sdp_style.css' %}">
    </head>
    <body>
        <!-- 내비게이션 -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-lg-5">
                <!-- <a class="navbar-brand" href="">Start Bootstrap</a> -->
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <!-- <li class="nav-item"><a class="nav-link" href="#!"></a></li>
                        <li class="nav-item"><a class="nav-link" href="#!"></a></li> -->
                        {% if user.username %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/logout">logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="/users/login/">login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        
        <!-- 헤더(계절 설정 가능) -->        
        <header class="py-3">
            <div class="container px-lg-5">
                <div class="p-4 p-lg-5 bg-light rounded-3 text-center">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-5 fw-bold">Season Dining Project</h1>
                        <p class="fs-1">🚗💨</p>
                        <!-- <p class="fs-5">나만의 축제 별 맛집을 찾아보세요!</p> -->
                        <a class="btn btn-outline-primary btn-lg" href="#!">봄　</a>
                        <a class="btn btn-outline-primary btn-lg" href="#!">여름</a>
                        <a class="btn btn-outline-primary btn-lg" href="#!">가을</a>
                        <a class="btn btn-outline-primary btn-lg" href="#!">겨울</a>
                        <a class="btn btn-outline-primary btn-lg" href="#!">시즌프리</a>
                    </div>
                </div>
            </div>
        </header>
        
        <!-- 권역 설정 -->
        <section class="pt-4">
            <div class="container px-lg-5">                
                <div class="row gx-lg-5">
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-warning bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">수도권</a></h2>
                                <p class="mb-0 mt-2">서울, 인천, 경기도</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-warning bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">강원권</a></h2>
                                <p class="mb-0 mt-2">강원특별자치도</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-warning bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">충청권<a></h2>
                                <p class="mb-0 mt-2">대전, 세종<br />충청북도, 충청남도</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-success bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">영남권</a></h2>
                                <p class="mb-0 mt-2">대구, 부산, 울산,<br/>경상북도, 경상남도</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-success bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">호남권</a></h2>
                                <p class="mb-0 mt-2">광주, <br />전북특별자치도, 전라남도</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-xxl-4 mb-5">
                        <div class="card bg-light border-0 h-100">
                            <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                                <div class="feature bg-success bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid fa-map-location-dot"></i></div>
                                <h2 class="fs-4 fw-bold"><a href="{% url 'markets:market_list' %}">제주권</a></h2>
                                <p class="mb-0 mt-2">제주특별자치도</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; 여기가서먹조</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>     
    </body>
</html>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         